/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialRequestsIndexRouteImport } from './routes/material-requests/index'
import { Route as MaterialRequestsNewRouteImport } from './routes/material-requests/new'
import { Route as MaterialRequestsIdEditRouteImport } from './routes/material-requests/$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRequestsIndexRoute = MaterialRequestsIndexRouteImport.update({
  id: '/material-requests/',
  path: '/material-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRequestsNewRoute = MaterialRequestsNewRouteImport.update({
  id: '/material-requests/new',
  path: '/material-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRequestsIdEditRoute = MaterialRequestsIdEditRouteImport.update({
  id: '/material-requests/$id/edit',
  path: '/material-requests/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/material-requests/new': typeof MaterialRequestsNewRoute
  '/material-requests': typeof MaterialRequestsIndexRoute
  '/material-requests/$id/edit': typeof MaterialRequestsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/material-requests/new': typeof MaterialRequestsNewRoute
  '/material-requests': typeof MaterialRequestsIndexRoute
  '/material-requests/$id/edit': typeof MaterialRequestsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/material-requests/new': typeof MaterialRequestsNewRoute
  '/material-requests/': typeof MaterialRequestsIndexRoute
  '/material-requests/$id/edit': typeof MaterialRequestsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/material-requests/new'
    | '/material-requests'
    | '/material-requests/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/material-requests/new'
    | '/material-requests'
    | '/material-requests/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/material-requests/new'
    | '/material-requests/'
    | '/material-requests/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MaterialRequestsNewRoute: typeof MaterialRequestsNewRoute
  MaterialRequestsIndexRoute: typeof MaterialRequestsIndexRoute
  MaterialRequestsIdEditRoute: typeof MaterialRequestsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-requests/': {
      id: '/material-requests/'
      path: '/material-requests'
      fullPath: '/material-requests'
      preLoaderRoute: typeof MaterialRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-requests/new': {
      id: '/material-requests/new'
      path: '/material-requests/new'
      fullPath: '/material-requests/new'
      preLoaderRoute: typeof MaterialRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-requests/$id/edit': {
      id: '/material-requests/$id/edit'
      path: '/material-requests/$id/edit'
      fullPath: '/material-requests/$id/edit'
      preLoaderRoute: typeof MaterialRequestsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MaterialRequestsNewRoute: MaterialRequestsNewRoute,
  MaterialRequestsIndexRoute: MaterialRequestsIndexRoute,
  MaterialRequestsIdEditRoute: MaterialRequestsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
